name: 'OpenAPI Spec Finder'
description: 'Find OpenAPI Specifications in the repository'
inputs:
  repository:
    description: 'GitHub repository URL'
    required: false
  search-dir:
    description: 'Directory to search'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repository }}
    - ${{ inputs.search-dir }}
outputs:
  spec_files:
    value: ${{ steps.find-specs.outputs.spec_files }}
